theme: jekyll-theme-minimal

title: YiArea

name: YiArea
email: firefivy@hotmail.com
author: Lix Yang

description: Desc
meta_description: Desc_M
motto: Motto
banner: Banner

github: https://github.com/YiArea/
github_username: YiArea