theme: jekyll-theme-minimal

title: YiArea

name: YiArea
email: firefivy@hotmail.com
author: Lix Yang

url: https://YiArea.com/
# baseurl: "/index"

description: 会拍照的业余码农~ 爱旅行，好装13，还准备学做菜...
meta_description: Desc1212123
motto: Motto
banner: Banner

github: https://github.com/YiArea/
github_username: YiArea
